#!/bin/bash

echo ""
echo ">>"
echo ">> Deploying Vault"
echo ">>"

cd /root/terraform/vault
nohup terraform apply -refresh=false -auto-approve > /root/terraform/vault/terraform.out &
sleep 10

echo ""
echo ">>"
echo ">> Deploying HCS cluster"
echo ">>"

cd /root/terraform/hcs
terraform apply -refresh=false -auto-approve > /root/terraform/hcs/terraform.out
sleep 120

exit 0
