#!/bin/sh
#

set-workdir /root/terraform/panw-config

cd /root/terraform/bigip
terraform output > /info.txt

cd /root/terraform/panw-vm
terraform output >> /info.txt

cd /root/terraform/panw-config
terraform init

bastion_ip=$(terraform output -state /root/terraform/vnet/terraform.tfstate bastion_ip)
firewall_ip=$(terraform output -state /root/terraform/panw-vm/terraform.tfstate FirewallIP)
pa_username=$(terraform output -state /root/terraform/panw-vm/terraform.tfstate pa_username)
pa_password=$(terraform output -state /root/terraform/panw-vm/terraform.tfstate pa_password)
echo "export bastion_ip=${bastion_ip}" >> ~/.bashrc
echo "export firewall_ip=${firewall_ip}" >> ~/.bashrc

cat << EOF > /root/terraform/panos_commit/panos-commit.json
{
    "hostname": "${firewall_ip}",
    "username": "${pa_username}",
    "password": "${pa_password}",
    "sleep": 15
}
EOF

exit 0
