#!/bin/sh
#
# This is a sample solve script. Rename this file to solve-$CONTAINER
# (where $container is the name of the container as defined in your config.yml),
# and replace this content with your own script.
#
# This script will be run when you solve the challenge.
#
# Remember that the exit code is important. See the documentation
# for more information.
#

echo ""
echo ">>"
echo ">> Configuring Palo Alto Firewall"
echo ">>"

#let it finish booting.
sleep 30

cd /root/terraform/panw-config
terraform apply -refresh=false -auto-approve > /root/terraform/panw-config/terraform.out

sleep 10

# Commit the changes
/root/terraform/panos_commit/panos-commit -config /root/terraform/panos_commit/panos-commit.json
sleep 10

exit 0
