#!/bin/bash

# Allow instruqt time to do its thing
sleep 10

eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_rsa

bastion_ip=$(terraform output -state /root/terraform/vnet/terraform.tfstate bastion_ip)
echo "export bastion_ip=${bastion_ip}" >> ~/.bashrc

# From git clone https://github.com/hashicorp/workshop-consul-terraform-sync.git
cd /root/terraform/consul-terraform-sync/
terraform init

##creds
vault login -method=userpass username=operations password=Password1
export CONSUL_HTTP_TOKEN=$(vault read -field token consul/creds/ops)

consulconfig=$(az resource show --ids "/subscriptions/$(az account show | jq -r .id)/resourceGroups/$(terraform output -state /root/terraform/vnet/terraform.tfstate resource_group_name)/providers/Microsoft.Solutions/applications/hcs/customconsulClusters/hashicorp-consul-cluster" --api-version 2018-09-01-preview | jq -r .properties.consulConfigFile | base64 -d)
ca_cert=$(az resource show --ids "/subscriptions/$(az account show | jq -r .id)/resourceGroups/$(terraform output -state /root/terraform/vnet/terraform.tfstate resource_group_name)/providers/Microsoft.Solutions/applications/hcs/customconsulClusters/hashicorp-consul-cluster" --api-version 2018-09-01-preview | jq -r .properties.consulCaFile | base64 -d)
token=$(vault kv get -field=master_token secret/consul)
bigip_mgmt_addr=$(terraform output -state=/root/terraform/bigip/terraform.tfstate mgmt_ip)
bigip_admin_user=$(terraform output -state=/root/terraform/bigip/terraform.tfstate f5_username)
bigip_admin_passwd=$(terraform output -state=/root/terraform/bigip/terraform.tfstate f5_password)

cat << EOF > /root/terraform/consul-terraform-sync/terraform.tfvars
ssh_public_key = "$(cat ~/.ssh/id_rsa.pub)"
endpoint = "${endpoint}"
consulconfig = <<-EOT
${consulconfig}
EOT
ca_cert = <<-EOT
${ca_cert}
EOT
consul_token = "${token}"
bigip_mgmt_addr = "${bigip_mgmt_addr}"
bigip_admin_user = "${bigip_admin_user}"
bigip_admin_passwd = "${bigip_admin_passwd}"
EOF

exit 0
