#!/bin/bash

echo ">> Deploying PANW FW VM"

cd /root/terraform/panw-vm
nohup terraform apply -auto-approve > /root/terraform/panw-vm/terraform.out &

echo ">> Deploying BIG-IP VM"

cd /root/terraform/bigip
terraform apply -refresh=false -auto-approve > /root/terraform/bigip/terraform.out

#block HCS
while [ -f /root/terraform/hcs/.terraform.tfstate.lock.info ]; do echo 'hcs still provisioning'; sleep 5;  done

#block PANW FW
while [ -f /root/terraform/panw-vm/.terraform.tfstate.lock.info ]; do echo 'PANW still provisioning'; sleep 5;  done

sleep 30
exit 0

