#!/bin/sh
#

set-workdir /root/terraform/panw

cd /root/terraform/panw
terraform init

bastion_ip=$(terraform output -state /root/terraform/vnet/terraform.tfstate bastion_ip)
firewall_ip=$(terraform output -state /root/terraform/panw/terraform.tfstate FirewallIP)

az vm image terms accept --urn paloaltonetworks:vmseries1:bundle1:latest

exit 0
